# Generated by Django 5.2.4 on 2026-07-05 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.CharField(max_length=320)),
                ('content', models.TextField()),
                ('cover_image_url', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('published', 'Опубліковано')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=220)),
                ('issuer', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.CharField(blank=True, max_length=500)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('is_ready', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('contact_method', models.CharField(choices=[('telegram', 'Telegram'), ('phone', 'Телефон'), ('email', 'Email')], max_length=20)),
                ('contact_value', models.CharField(max_length=180)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(default='portfolio', max_length=120)),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_progress', 'У роботі'), ('contacted', 'Зв’язалися'), ('closed', 'Закрита')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(default='Загальне', max_length=120)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=120)),
                ('tagline', models.CharField(max_length=240)),
                ('price_uah', models.PositiveIntegerField()),
                ('duration', models.CharField(blank=True, max_length=120)),
                ('features', models.JSONField(blank=True, default=list)),
                ('highlighted', models.BooleanField(default=False)),
                ('complexity_note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(max_length=120)),
                ('client', models.CharField(blank=True, max_length=180)),
                ('summary', models.CharField(max_length=320)),
                ('challenge', models.TextField()),
                ('solution', models.TextField()),
                ('result_text', models.TextField()),
                ('live_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=120)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=list)),
                ('metrics', models.JSONField(blank=True, default=list)),
                ('cover_image_url', models.CharField(blank=True, max_length=500)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('featured', models.BooleanField(default=False)),
                ('ai_integration', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('published', 'Опубліковано'), ('draft', 'Чернетка'), ('concept', 'Концепт')], default='published', max_length=20)),
                ('is_verified_case', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.CharField(max_length=260)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='sparkles', max_length=40)),
                ('price_from_uah', models.PositiveIntegerField(default=5000)),
                ('duration', models.CharField(blank=True, max_length=120)),
                ('complexity', models.CharField(default='Стандартна', max_length=80)),
                ('features', models.JSONField(blank=True, default=list)),
                ('premium_note', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Ковтунович Дмитро Валерійович', max_length=160)),
                ('role', models.CharField(default='Full-stack developer', max_length=120)),
                ('city', models.CharField(default='Рівне, Україна', max_length=120)),
                ('age', models.PositiveIntegerField(default=18)),
                ('years_experience', models.PositiveIntegerField(default=4)),
                ('availability', models.CharField(default='Відкритий до нових проєктів', max_length=160)),
                ('logo_text', models.CharField(default='DK.', max_length=40)),
                ('hero_title', models.CharField(max_length=280)),
                ('hero_subtitle', models.TextField()),
                ('about_short', models.TextField()),
                ('about_full', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('telegram', models.CharField(max_length=80)),
                ('instagram', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('working_hours', models.CharField(default='Щодня, 10:00–22:00', max_length=80)),
                ('resume_url', models.URLField(blank=True)),
                ('socials', models.JSONField(blank=True, default=dict)),
                ('currency_rates', models.JSONField(blank=True, default=dict)),
                ('seo_title', models.CharField(blank=True, max_length=180)),
                ('seo_description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.CharField(max_length=160)),
                ('role', models.CharField(blank=True, max_length=160)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('text', models.TextField()),
                ('photo_url', models.CharField(blank=True, max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='portfolio.project')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
