# Generated by Django 5.2.4 on 2026-07-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_kicker', models.CharField(default='Моя історія · Full-stack developer', max_length=180)),
                ('hero_title', models.CharField(default='Чотири роки тому — лише мрія. Сьогодні — продукти для реального бізнесу.', max_length=320)),
                ('hero_text', models.TextField(default='Я Дмитро, мені 18. Самостійно створюю сучасні сайти, вебсистеми та AI-інтеграції — від першої ідеї до запуску й подальшого розвитку.')),
                ('hero_photo', models.ImageField(blank=True, null=True, upload_to='about/portrait/')),
                ('hero_photo_alt', models.CharField(default='Портрет Дмитра Ковтуновича', max_length=220)),
                ('story_title', models.CharField(default='Я не прокинувся програмістом за одну ніч. Я поступово ним став.', max_length=320)),
                ('story_text', models.TextField(default='Мій шлях почався з мрії стати програмістом і перших невеликих програм. Чотири роки навчання перетворили окремі знання на вміння створювати повноцінні цифрові продукти.')),
                ('journey', models.JSONField(blank=True, default=list)),
                ('stats', models.JSONField(blank=True, default=list)),
                ('babyland_title', models.CharField(default='Диплом був фіналом навчання. BABY LAND став початком професійної роботи.', max_length=320)),
                ('babyland_text', models.TextField(default='За два тижні я самостійно створив повноцінний продукт для приватного дитячого садка: дизайн, frontend, backend, базу даних, форми та кастомну адмінпанель.')),
                ('ai_title', models.CharField(default='Я не зупиняюся на звичайній веброзробці.', max_length=320)),
                ('ai_text', models.TextField(default='Наступна ціль — системи, які не просто показують інформацію, а самі виконують частину роботи бізнесу.')),
                ('ai_items', models.JSONField(blank=True, default=list)),
                ('education_title', models.CharField(default='Диплом на відмінно — не фінальна точка, а підтвердження фундаменту.', max_length=320)),
                ('education_text', models.TextField(default='Чотири роки навчання дали мені базу, а реальні проєкти навчили відповідати за результат.')),
                ('college_name', models.CharField(default='ВСП «Рівненський фаховий коледж НУБіП України»', max_length=260)),
                ('diploma_title', models.CharField(default='Захищено на відмінно', max_length=220)),
                ('diploma_description', models.TextField(default='Диплом підтверджує фундамент, на якому я продовжую будувати реальні продукти.')),
                ('diploma_file', models.FileField(blank=True, null=True, upload_to='about/documents/')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='about/documents/')),
                ('final_title', models.CharField(default='Мені 18. Я вже створюю продукти. І це лише початок.', max_length=320)),
                ('final_text', models.TextField(default='Потрібен сучасний сайт, продумана вебсистема або автоматизація процесів? Розкажіть про задачу — я запропоную реалістичний шлях від ідеї до запуску.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/covers/'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/covers/'),
        ),
    ]
