# Generated by Django 5.2.4 on 2026-07-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_aboutpage_blogpost_cover_image_project_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='final_kicker',
            field=models.CharField(default='Зараз я відкритий до нових проєктів', max_length=180),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='journey_heading',
            field=models.CharField(default='Від першого рядка коду до продукту, яким користується бізнес.', max_length=320),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='journey_intro',
            field=models.TextField(default='Не ідеальна пряма лінія, а послідовність складних задач, помилок, рішень і відчутного прогресу.'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='principles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='principles_title',
            field=models.CharField(default='Дизайн привертає увагу. Система утримує цінність.', max_length=320),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='project_facts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='story_support_text',
            field=models.TextField(default='Мій головний принцип простий: продукт має не лише красиво виглядати, а й вирішувати конкретну задачу — приносити заявки, структурувати дані, економити час або автоматизувати рутинний процес.'),
        ),
    ]
