# Generated by Django 5.2.4 on 2026-07-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_contactlead_notifications_and_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=64, unique=True)),
                ('user_id', models.CharField(blank=True, max_length=64)),
                ('username', models.CharField(blank=True, max_length=120)),
                ('first_name', models.CharField(blank=True, max_length=160)),
                ('last_name', models.CharField(blank=True, max_length=160)),
                ('language_code', models.CharField(blank=True, max_length=16)),
                ('is_notification_recipient', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('last_command', models.CharField(blank=True, max_length=120)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_notification_recipient', '-last_seen_at', 'username', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='contactlead',
            name='budget',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='last_contact_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='next_action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='page_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='service',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='telegram',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='utm_source',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactlead',
            name='status',
            field=models.CharField(choices=[('new', 'Нова'), ('viewed', 'Переглянута'), ('in_progress', 'У роботі'), ('waiting_client', 'Очікує відповіді клієнта'), ('completed', 'Завершена'), ('rejected', 'Відхилена'), ('spam', 'Спам')], default='new', max_length=20),
        ),
    ]
