# Generated by Django 5.2.4 on 2026-07-06 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_telegrambotuser_contactlead_budget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media-library/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media-library/thumbnails/%Y/%m/')),
                ('title', models.CharField(max_length=220)),
                ('original_name', models.CharField(blank=True, max_length=260)),
                ('alt_text', models.CharField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=260)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Головна'), ('about', 'Про мене'), ('projects', 'Проєкти'), ('project_detail', 'Детальна сторінка проєкту'), ('services', 'Послуги'), ('pricing', 'Ціни'), ('blog', 'Блог'), ('blog_detail', 'Детальна сторінка статті'), ('contact', 'Контакти')], db_index=True, max_length=60)),
                ('section_type', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('icon', models.CharField(default='layout', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['page', 'order', 'id'],
                'unique_together': {('page', 'section_type')},
            },
        ),
        migrations.CreateModel(
            name='EditorDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(blank=True, max_length=80)),
                ('page_key', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('server_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('entity_type', 'entity_id', 'page_key', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SeoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(db_index=True, max_length=120)),
                ('content_type', models.CharField(default='page', max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('path', models.CharField(blank=True, max_length=260)),
                ('seo_title', models.CharField(blank=True, max_length=180)),
                ('seo_description', models.TextField(blank=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=180)),
                ('canonical_url', models.CharField(blank=True, max_length=300)),
                ('og_title', models.CharField(blank=True, max_length=180)),
                ('og_description', models.TextField(blank=True)),
                ('og_image_url', models.CharField(blank=True, max_length=500)),
                ('index', models.BooleanField(default=True)),
                ('follow', models.BooleanField(default=True)),
                ('focus_keyword', models.CharField(blank=True, max_length=160)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='og_entries', to='portfolio.mediaasset')),
            ],
            options={
                'ordering': ['page_key'],
                'unique_together': {('content_type', 'page_key', 'object_id')},
            },
        ),
    ]
