import { useMemo, useState } from 'react'
import { ArrowDown, ArrowUpRight, Bot, CheckCircle2, Database, FilePenLine, Globe2, Sparkles } from 'lucide-react'
import { useLanguage } from '../../i18n/LanguageContext'

const tabs = {
  uk: [
    { id:'site', label:'Сайт', icon:Globe2, eyebrow:'Публічна частина', title:'Сайт, який веде до заявки', status:'LIVE', stats:[{label:'Нові звернення',value:'+07',note:'за цей тиждень'},{label:'Конверсійні точки',value:'06',note:'у структурі сайту'}], feed:[{title:'Відвідувач відкрив послугу',text:'Перейшов до форми консультації',time:'зараз'},{title:'Форму успішно надіслано',text:'Контакт збережено в системі',time:'12 с'},{title:'Менеджеру створено задачу',text:'Заявка вже готова до обробки',time:'1 хв'}]},
    { id:'leads', label:'Заявки', icon:Database, eyebrow:'Робочий простір', title:'Усі звернення в одному місці', status:'SYNC', stats:[{label:'Нові ліди',value:'07',note:'потребують відповіді'},{label:'У роботі',value:'12',note:'зі збереженою історією'}], feed:[{title:'Нова заявка з сайту',text:'Бюджет і послуга вже зазначені',time:'зараз'},{title:'Статус змінено',text:'Клієнт перейшов у «Переговори»',time:'4 хв'},{title:'Нагадування заплановано',text:'Система не дасть втратити контакт',time:'1 год'}]},
    { id:'ai', label:'AI', icon:Bot, eyebrow:'Автоматизація', title:'AI бере на себе повторювані дії', status:'ONLINE', stats:[{label:'AI-сценарії',value:'04',note:'активні зараз'},{label:'Чернетки відповідей',value:'19',note:'підготовлено за день'}], feed:[{title:'AI визначив запит клієнта',text:'Потрібен сайт із адмінпанеллю',time:'зараз'},{title:'Відповідь підготовлено',text:'Менеджеру залишилось перевірити',time:'8 с'},{title:'Лід кваліфіковано',text:'Бюджет і строки додано до картки',time:'22 с'}]},
    { id:'content', label:'Контент', icon:Sparkles, eyebrow:'Керування сайтом', title:'Оновлення без звернення до розробника', status:'READY', stats:[{label:'Матеріали',value:'32',note:'опубліковано'},{label:'Чернетки',value:'05',note:'готові до перевірки'}], feed:[{title:'Створено нову сторінку',text:'Структуру збережено автоматично',time:'зараз'},{title:'Фото оптимізовано',text:'Сайт залишиться швидким',time:'16 с'},{title:'Зміни опубліковано',text:'Новий контент уже бачать клієнти',time:'2 хв'}]},
  ],
  en: [
    { id:'site', label:'Website', icon:Globe2, eyebrow:'Public website', title:'A website that guides visitors toward an inquiry', status:'LIVE', stats:[{label:'New inquiries',value:'+07',note:'this week'},{label:'Conversion points',value:'06',note:'across the website'}], feed:[{title:'Visitor opened a service',text:'Moved to the consultation form',time:'now'},{title:'Form submitted successfully',text:'The contact was saved in the system',time:'12 sec'},{title:'Task created for a manager',text:'The inquiry is ready for processing',time:'1 min'}]},
    { id:'leads', label:'Leads', icon:Database, eyebrow:'Workspace', title:'Every inquiry in one place', status:'SYNC', stats:[{label:'New leads',value:'07',note:'need a reply'},{label:'In progress',value:'12',note:'with full history'}], feed:[{title:'New website inquiry',text:'Budget and service are already specified',time:'now'},{title:'Status updated',text:'The client moved to “Negotiation”',time:'4 min'},{title:'Reminder scheduled',text:'The system will not lose the contact',time:'1 hr'}]},
    { id:'ai', label:'AI', icon:Bot, eyebrow:'Automation', title:'AI handles repetitive actions', status:'ONLINE', stats:[{label:'AI scenarios',value:'04',note:'active now'},{label:'Reply drafts',value:'19',note:'prepared today'}], feed:[{title:'AI identified the client’s request',text:'A website with an admin panel is needed',time:'now'},{title:'Reply prepared',text:'A manager only needs to review it',time:'8 sec'},{title:'Lead qualified',text:'Budget and deadline added to the card',time:'22 sec'}]},
    { id:'content', label:'Content', icon:Sparkles, eyebrow:'Website management', title:'Updates without contacting a developer', status:'READY', stats:[{label:'Published items',value:'32',note:'online'},{label:'Drafts',value:'05',note:'ready for review'}], feed:[{title:'New page created',text:'The structure was saved automatically',time:'now'},{title:'Image optimized',text:'The website will stay fast',time:'16 sec'},{title:'Changes published',text:'Clients can already see the new content',time:'2 min'}]},
  ],
}

const copy = {
  uk: { kicker:'Full-stack розробка · дизайн · автоматизація', titleA:'Створюю цифрові продукти,', titleB:' які працюють на бізнес.', lead:'Від першої ідеї до готового запуску: продумую структуру, створюю сучасний інтерфейс, backend, базу даних і зручне керування — щоб сайт приносив заявки, а не просто займав місце в інтернеті.', discuss:'Обговорити проєкт', works:'Подивитися роботи', proofs:['Повний цикл розробки','Кастомна адмінпанель','Підтримка після запуску'], demo:'Інтерактивна демонстрація бізнес-системи', demoNav:'Розділи демонстрації', click:'Демо можна поклікати', floatingA:'сайт приймає звернення', floatingB:'для керування бізнесом' },
  en: { kicker:'Full-stack development · design · automation', titleA:'I build digital products', titleB:' that work for business.', lead:'From the first idea to a complete launch, I design the structure, build a modern interface, backend, database, and convenient management tools — so the website generates inquiries instead of simply occupying space online.', discuss:'Discuss a project', works:'View projects', proofs:['Full-cycle development','Custom admin panel','Support after launch'], demo:'Interactive business system demo', demoNav:'Demo sections', click:'The demo is interactive', floatingA:'the website receives inquiries', floatingB:'for business management' },
}

export default function HomeHero({ settings, telegram }) {
  const { language } = useLanguage()
  const systemTabs = tabs[language]
  const c = copy[language]
  const [activeTab, setActiveTab] = useState('site')
  const panel = useMemo(() => systemTabs.find((item) => item.id === activeTab) || systemTabs[0], [systemTabs, activeTab])
  return <section className="sales3-hero" id="top"><div className="sales3-shell sales3-hero-grid">
    <div className="sales3-hero-copy">
      <div className="sales3-availability" data-sales-reveal><span><i /> {settings.availability}</span><b>{settings.city}</b></div>
      <p className="sales3-kicker" data-sales-reveal>{c.kicker}</p>
      <h1 data-sales-reveal>{c.titleA}<em>{c.titleB}</em></h1>
      <p className="sales3-hero-lead" data-sales-reveal>{c.lead}</p>
      <div className="sales3-hero-actions" data-sales-reveal><a className="sales3-btn sales3-btn-primary" href={telegram} target="_blank" rel="noreferrer"><span>{c.discuss}</span><ArrowUpRight size={18} /></a><a className="sales3-btn sales3-btn-secondary" href="#cases"><span>{c.works}</span><ArrowDown size={17} /></a></div>
      <div className="sales3-proof-line" data-sales-reveal>{c.proofs.map((item) => <span key={item}><CheckCircle2 size={17} /> {item}</span>)}</div>
    </div>
    <div className="sales3-hero-system" data-sales-reveal aria-label={c.demo}><div className="sales3-system-glow" /><div className="sales3-system-window"><div className="sales3-system-bar"><div><i /><i /><i /></div><span>business-system.local</span><b>ONLINE</b></div><div className="sales3-system-dashboard"><aside><strong>DK<span>.</span></strong><nav aria-label={c.demoNav}>{systemTabs.map((tab) => { const Icon = tab.icon; const active = tab.id === activeTab; return <button key={tab.id} type="button" className={active ? 'is-active' : ''} aria-pressed={active} onClick={() => setActiveTab(tab.id)}><Icon size={15} /><span>{tab.label}</span></button> })}</nav><div className="sales3-system-side-note"><FilePenLine size={14} /><span>{c.click}</span></div></aside><div className="sales3-system-main" key={panel.id}><header><div><small>{panel.eyebrow}</small><h3>{panel.title}</h3></div><span><i /> {panel.status}</span></header><div className="sales3-system-stats">{panel.stats.map((stat) => <article key={stat.label}><small>{stat.label}</small><strong>{stat.value}</strong><span>{stat.note}</span></article>)}</div><div className="sales3-activity-feed">{panel.feed.map((item, index) => <div key={item.title} className={index === 0 ? 'is-new' : ''}><i>{String(index + 1).padStart(2, '0')}</i><span><b>{item.title}</b><small>{item.text}</small></span><em>{item.time}</em></div>)}</div></div></div></div>
      <div className="sales3-floating-note sales3-floating-note-a"><span>24/7</span><small>{c.floatingA}</small></div><div className="sales3-floating-note sales3-floating-note-b"><span>1 {language === 'en' ? 'dashboard' : 'панель'}</span><small>{c.floatingB}</small></div>
    </div>
  </div><div className="sales3-shell sales3-hero-strip" data-sales-reveal><span>Python / Django</span><span>React</span><span>Custom Admin</span><span>AI Integration</span><span>Business Automation</span></div></section>
}
