import { CheckCircle2, FileText, Image as ImageIcon } from 'lucide-react'
import AboutAdminLayout from './AboutAdminLayout'
import useAboutAdmin from './useAboutAdmin'
import ImageCropUploader from '../../../components/admin/ImageCropUploader'
import FileUploader from '../../../components/admin/FileUploader'
export default function AboutDocumentsAdmin(){ const editor=useAboutAdmin([]); const statuses=[['Портрет',Boolean(editor.form.hero_photo_url),ImageIcon],['Обкладинка кейсу',Boolean(editor.babyland.uploaded_cover_url),ImageIcon],['Резюме',Boolean(editor.form.resume_file_url),FileText],['Диплом',Boolean(editor.form.diploma_file_url),FileText]]; return <AboutAdminLayout sectionKey="documents" title="Фото й документи" description="Усі файли сторінки в одному компактному менеджері." hideSave>
  <div className="about-admin-v3-file-status">{statuses.map(([label,ready,Icon])=><article key={label} className={ready?'ready':''}><span><Icon size={16}/></span><div><strong>{label}</strong><small>{ready?'Файл підключено':'Потрібно додати'}</small></div>{ready&&<CheckCircle2 size={17}/>}</article>)}</div>
  <div className="about-admin-v3-document-grid"><ImageCropUploader title="Портрет 4:5" hint="Перетягни фото, відрегулюй масштаб і кадрування." currentUrl={editor.form.hero_photo_url} uploadUrl="/about-page/upload/" removeUrl="/about-page/remove_file/" field="hero_photo" aspect={4/5} onUploaded={editor.applySavedData}/><ImageCropUploader title="Скриншот BABY LAND" hint="Формат 16:10 для публічної частини кейсу." currentUrl={editor.babyland.uploaded_cover_url} uploadUrl={`/projects/${editor.babyland.slug || 'baby-land'}/upload_cover/`} removeUrl={`/projects/${editor.babyland.slug || 'baby-land'}/remove_cover/`} aspect={16/10} onUploaded={editor.setBabyland}/><FileUploader title="Резюме" hint="PDF. Посилання з’явиться на першому екрані автоматично." currentUrl={editor.form.resume_file_url} field="resume_file" onUploaded={editor.applySavedData}/><FileUploader title="Диплом" hint="PDF або зображення. Після завантаження кнопка стане активною." currentUrl={editor.form.diploma_file_url} field="diploma_file" onUploaded={editor.applySavedData}/></div>
</AboutAdminLayout> }
